using System.Collections.Generic;
using Godot;

namespace Isolith.Core;

/// <summary>
/// A small pool of one-shot sound players.
/// </summary>
/// <remarks>
/// Every clip is generated by <c>tools/generate_assets.py</c> rather than
/// sourced externally (see <c>ASSETS.md</c>). If the generated files are absent
/// — a fresh clone before the generator has been run — playback is silently
/// skipped so the game still runs.
/// </remarks>
[GlobalClass]
public partial class Sfx : Node
{
    public const string Jump = "jump";
    public const string Land = "land";
    public const string Collect = "collect";
    public const string Bounce = "bounce";
    public const string Death = "death";
    public const string Complete = "complete";

    private const int VoiceCount = 8;

    private readonly Dictionary<string, AudioStream> _clips = new();
    private readonly List<AudioStreamPlayer> _voices = new();
    private int _next;

    public override void _Ready()
    {
        // Keep playing while the tree is paused, so menu sounds still work.
        ProcessMode = ProcessModeEnum.Always;

        foreach (string name in new[] { Jump, Land, Collect, Bounce, Death, Complete })
            Load(name);

        for (int i = 0; i < VoiceCount; i++)
        {
            var player = new AudioStreamPlayer { Name = $"Voice{i}", ProcessMode = ProcessModeEnum.Always };
            AddChild(player);
            _voices.Add(player);
        }
    }

    /// <summary>Plays a clip if it was generated; otherwise does nothing.</summary>
    /// <param name="volumeDb">Attenuation in decibels, relative to the clip.</param>
    public void Play(string name, float volumeDb = 0.0f)
    {
        if (!_clips.TryGetValue(name, out AudioStream? stream) || _voices.Count == 0)
            return;

        // Round-robin so overlapping sounds don't cut each other off.
        AudioStreamPlayer voice = _voices[_next];
        _next = (_next + 1) % _voices.Count;

        voice.Stream = stream;
        voice.VolumeDb = volumeDb;
        voice.Play();
    }

    private void Load(string name)
    {
        string path = $"res://assets/audio/{name}.wav";

        if (!ResourceLoader.Exists(path))
            return;

        if (ResourceLoader.Load(path) is AudioStream stream)
            _clips[name] = stream;
    }
}
