using System.Collections.Generic;
using Godot;

namespace Isolith.Core;

/// <summary>
/// A small pool of one-shot sound players.
/// </summary>
/// <remarks>
/// Every clip is generated by <c>tools/generate_assets.py</c> rather than
/// sourced externally (see <c>ASSETS.md</c>). If the generated files are absent
/// — a fresh clone before the generator has been run — playback is silently
/// skipped so the game still runs.
/// </remarks>
[GlobalClass]
public partial class Sfx : Node
{
    public const string Jump = "jump";
    public const string Land = "land";
    public const string Collect = "collect";
    public const string Bounce = "bounce";
    public const string Death = "death";
    public const string Complete = "complete";

    private const int VoiceCount = 8;

    private readonly Dictionary<string, AudioStream> _clips = new();
    private readonly List<AudioStreamPlayer> _voices = new();
    private int _next;

    public override void _Ready()
    {
        // Keep playing while the tree is paused, so menu sounds still work.
        ProcessMode = ProcessModeEnum.Always;

        foreach (string name in new[] { Jump, Land, Collect, Bounce, Death, Complete })
            Load(name);

        for (int i = 0; i < VoiceCount; i++)
        {
            var player = new AudioStreamPlayer { Name = $"Voice{i}", ProcessMode = ProcessModeEnum.Always };
            AddChild(player);
            _voices.Add(player);
        }
    }

    public override void _ExitTree()
    {
        // Drop every stream reference explicitly. These are RefCounted
        // resources held by a managed dictionary, and C# finalisation is not
        // guaranteed to run before the engine tears down its resource
        // registry — without this, Godot reports them as leaked at exit.
        foreach (AudioStreamPlayer voice in _voices)
        {
            voice.Stop();
            voice.Stream = null;
        }

        // Disposing releases the native reference immediately. Merely dropping
        // the managed reference would wait on the GC, which is not guaranteed
        // to run before the engine tears down its resource registry.
        foreach (AudioStream clip in _clips.Values)
            clip.Dispose();

        _voices.Clear();
        _clips.Clear();
    }

    /// <summary>Plays a clip if it was generated; otherwise does nothing.</summary>
    /// <param name="volumeDb">Attenuation in decibels, relative to the clip.</param>
    public void Play(string name, float volumeDb = 0.0f)
    {
        if (!_clips.TryGetValue(name, out AudioStream? stream) || _voices.Count == 0)
            return;

        float effects = Settings.EffectsVolume;

        // Silence is a real setting, not a very quiet one: -80 dB voices still
        // occupy the pool and cut off the sounds behind them.
        if (effects <= 0.001f)
            return;

        // Round-robin so overlapping sounds don't cut each other off.
        AudioStreamPlayer voice = _voices[_next];
        _next = (_next + 1) % _voices.Count;

        voice.Stream = stream;

        // Per-clip attenuation plus the player's effects level. Master volume is
        // not applied here — that one rides on the Master bus, so it also covers
        // anything that is not an effect.
        voice.VolumeDb = volumeDb + Mathf.LinearToDb(effects);
        voice.Play();
    }

    private void Load(string name)
    {
        string path = $"res://assets/audio/{name}.wav";

        if (!ResourceLoader.Exists(path))
            return;

        if (ResourceLoader.Load(path) is AudioStream stream)
            _clips[name] = stream;
    }
}
